---
# tasks file for nodeexporter_add_prometheus

# - shell: grep "instance_ip:9600" /etc/prometheus/prometheus.yml
#   register: test_grep

- name: remove host from prometheus properties
  blockinfile:
    path: /etc/prometheus/prometheus.yml
    state: absent
    marker: "# {mark} ANSIBLE MANAGED BLOCK insertion instance_name"
    block: |2 # that means it uses two line space for next line
        - job_name: 'instance_name'
          scrape_interval: 10s 
          static_configs:
            - targets: ['instance_ip:9600']

- name: Restart prometheus service
  ansible.builtin.service:
     name: prometheus
     state: restarted