# # Add microsoft packages repository and install moby engine ##

- name: Add an Apt signing key, uses whichever key is at the URL
  ansible.builtin.apt_key:
    url: https://packages.microsoft.com/keys/microsoft.asc
    state: present

- name: Add specified repository into sources list
  ansible.builtin.apt_repository:
    repo: deb https://packages.microsoft.com/ubuntu/18.04/prod bionic main
    state: present

# update cache
- name: Update repositories cache 
  apt:
    update_cache: yes


- name: Pause for 1 minutes
  pause:
    minutes: 1

- name: Remove packages
  apt:
    name: "{{ item }}"
    state: absent
  with_items:
       - containerd
       - containerd.io
       - docker-ce
       - docker-ce-cli
       - docker.io
       - runc

- name: Update repositories cache 
  apt:
    update_cache: yes

- name: Update repositories cache and install nvidia-container-runtime package
  apt:
    name: nvidia-container-runtime
    update_cache: yes

- name: install packages
  apt:
    name: "{{ item }}"
    state: present
  with_items:
       - moby-engine
       - moby-cli
       - iotedge

## Download and extract nvidia-docker to prevent dependency clash with moby engine ##

- name: Download and extract nvidia-docker 
  shell: |
    apt download nvidia-docker2
    dpkg-deb -xv nvidia-docker2_*.deb /
    rm nvidia-docker2_*.deb

# Restart docker 

- name: Restart docker service
  ansible.builtin.service:
     name: docker
     state: restarted