
- stat: path=/usr/bin/nvidia-smi
  register: nvidia_smi_command_result

- include: tasks/cuda-nvidia.yaml
  when:  not nvidia_smi_command_result.stat.exists

- stat: path=/usr/bin/iotedge
  register: iotedge_command_result

- include: tasks/iotedge.yaml
  when:  not iotedge_command_result.stat.exists

# - stat: path=/usr/bin/telnet
#   register: st

# - include: tasks/test.yaml
#   when: not st.stat.exists