---
# tasks file for gpu_add_prometheus

- name: add host to properties
  blockinfile:
    path: /etc/prometheus/prometheus.yml
    marker: "# {mark} ANSIBLE MANAGED BLOCK insertion instance_name"
    block: |2 # that means it uses two line space for next line
        - job_name: 'gpu_metrics_instance_name'
          scrape_interval: 10s
          static_configs:
            - targets: ['instance_ip:9400']

- name: Restart prometheus service
  ansible.builtin.service:
     name: prometheus
     state: restarted