---
# tasks file for gpu_add_prometheus

- name: Check if host is added
  shell: grep -c "instance_ip:9400" /etc/prometheus/prometheus.yml || true
  register: test_grep


- name: add host to properties
  blockinfile:
    path: /etc/prometheus/prometheus.yml
    block: |2 # that means it uses two line space for next line
        - job_name: 'gpu_metrics_instance_name'
          scrape_interval: 10s
          static_configs:
            - targets: ['instance_ip:9400']
  when: test_grep.stdout == "0"