---
# tasks file for gpu_add_prometheus

- name: Stop the sandbox instances
  ec2:
    instance_ids: '{{ instance_ids }}'
    region: '{{ region }}'
    state: stopped
    wait: True
    #vpc_subnet_id: subnet-29e63245
    #assign_public_ip: yes
